package com.saleh.enezi;
import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,content; int green=Color.rgb(30,107,56); android.content.SharedPreferences sp;
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("enezi",0);show("home");}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.DKGRAY);v.setPadding(20,18,20,18);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,249,247));
 TextView h=t("🧺  "+title,22);h.setTextColor(Color.WHITE);h.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);h.setBackgroundColor(green);root.addView(h,new LinearLayout.LayoutParams(-1,70));
 content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,18,18,18);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void nav(){LinearLayout n=new LinearLayout(this);String[] a={"الرئيسية","فاتورة","العملاء"};for(String x:a){Button b=btn(x);b.setOnClickListener(v->show(x.equals("الرئيسية")?"home":x.equals("فاتورة")?"invoice":"customers"));n.addView(b,new LinearLayout.LayoutParams(0,65,1));}root.addView(n);}
 void show(String s){if(s.equals("home"))home();else if(s.equals("invoice"))invoice();else customers();}
 void home(){base("بقالة العنزي");content.addView(t("مرحباً بكم في بقالتكم المفضلة",26));content.addView(t("نظام الفواتير ودفتر الحسابات — يعمل محلياً بدون إنترنت",16));
 Button a=btn("🧾 إنشاء فاتورة مبيعات");a.setOnClickListener(v->show("invoice"));content.addView(a);Button c=btn("👥 دفتر الحسابات والعملاء");c.setOnClickListener(v->show("customers"));content.addView(c);nav();}
 void invoice(){base("إنشاء فاتورة");EditText customer=e("اسم العميل");content.addView(customer);EditText item=e("اسم الصنف");content.addView(item);EditText qty=e("الكمية", "1");content.addView(qty);EditText price=e("السعر / الإجمالي");content.addView(price);TextView total=t("الإجمالي: 0 ريال",24);content.addView(total);Button add=btn("+ إضافة الصنف");content.addView(add);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);add.setOnClickListener(v->{try{double q=Double.parseDouble(qty.getText().toString()),p=Double.parseDouble(price.getText().toString());TextView row=t(item.getText()+" × "+q+" = "+(q*p)+" ريال",17);list.addView(row);double old=Double.parseDouble(total.getText().toString().replaceAll("[^0-9.]",""));total.setText("الإجمالي: "+(old+q*p)+" ريال");item.setText("");qty.setText("1");price.setText("");}catch(Exception ignored){}});Button save=btn("💾 حفظ الفاتورة");content.addView(save);save.setOnClickListener(v->{sp.edit().putInt("invoices",sp.getInt("invoices",0)+1).apply();Toast.makeText(this,"تم حفظ الفاتورة",Toast.LENGTH_SHORT).show();});nav();}
 EditText e(String hint){return e(hint,"");}EditText e(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(17);e.setPadding(16,8,16,8);return e;}
 void customers(){base("العملاء ودفتر الحسابات");EditText n=e("اسم العميل");content.addView(n);Button add=btn("+ إضافة عميل");content.addView(add);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);String raw=sp.getString("customers","");if(!raw.isEmpty())for(String x:raw.split("\|"))if(!x.isEmpty())addCustomerRow(list,x);add.setOnClickListener(v->{String x=n.getText().toString().trim();if(x.isEmpty())return;String r=sp.getString("customers","");sp.edit().putString("customers",r+x+"|").apply();addCustomerRow(list,x);n.setText("");});nav();}
 void addCustomerRow(LinearLayout l,String name){Button b=btn(name+"   —   فتح الحساب");b.setOnClickListener(v->account(name));l.addView(b);}
 void account(String name){base("حساب العميل: "+name);TextView bal=t("الرصيد: "+sp.getFloat("bal_"+name,0)+" ريال",22);content.addView(bal);EditText amount=e("المبلغ");content.addView(amount);EditText details=e("التفاصيل");content.addView(details);Button debit=btn("عليه — إضافة مديونية");content.addView(debit);Button credit=btn("له — تسجيل دفعة");content.addView(credit);debit.setOnClickListener(v->tx(name,amount,details,bal,1));credit.setOnClickListener(v->tx(name,amount,details,bal,-1));nav();}
 void tx(String n,EditText a,EditText d,TextView bal,float sign){try{float x=Float.parseFloat(a.getText().toString());float old=sp.getFloat("bal_"+n,0);float now=old+x*sign;sp.edit().putFloat("bal_"+n,now).apply();bal.setText("الرصيد: "+now+" ريال");a.setText("");d.setText("");}catch(Exception ignored){}}
}